-- Adapted from
-- https://github.com/cpplain/flexoki.nvim
-- MIT License

vim.cmd.highlight("clear")
vim.g.colors_name = "flexoki"

-- Flexoki colors
local c = require("flexoki").c

-- Highlights
local function hl(name, val)
	vim.api.nvim_set_hl(0, name, val)
end

-- Editor highlights (:help highlight-groups)
hl("ColorColumn", { bg = c.bg2 })
hl("Conceal", { fg = c.tx3 })
hl("CurSearch", { bg = c.orange3 })
hl("Cursor", { fg = c.bg, bg = c.tx })
hl("lCursor", { link = "Cursor" })
hl("CursorIM", { link = "Cursor" })
hl("CursorColumn", { link = "CursorLine" })
hl("CursorLine", { bg = c.bg2 })
hl("Directory", { fg = c.blue })
hl("DiffAdd", { fg = c.green, bg = c.green4 })
hl("DiffChange", { fg = c.yellow, bg = c.yellow4 })
hl("DiffDelete", { fg = c.red, bg = c.red4 })
hl("DiffText", { bg = c.yellow3 })
hl("EndOfBuffer", { link = "NonText" })
hl("TermCursor", { link = "Cursor" })
hl("ErrorMsg", { fg = c.red })
hl("WinSeparator", { fg = c.ui })
hl("Folded", { fg = c.tx3, bg = c.bg2 })
hl("FoldColumn", { link = "SignColumn" })
hl("SignColumn", { fg = c.tx3 })
hl("IncSearch", { link = "CurSearch" })
hl("Substitute", { link = "Search" })
hl("LineNr", { fg = c.tx3 })
hl("LineNrAbove", { link = "LineNr" })
hl("LineNrBelow", { link = "LineNr" })
hl("CursorLineNr", { link = "CursorLine" })
hl("CursorLineFold", { link = "CursorLineSign" })
hl("CursorLineSign", { fg = c.tx3, bg = c.bg2 })
hl("MatchParen", { fg = c.tx2, bold = true })
hl("ModeMsg", { fg = c.tx2 })
hl("MsgArea", {})
hl("MsgSeparator", { link = "StatusLine" })
hl("MoreMsg", { link = "Normal" })
hl("NonText", { fg = c.tx3 })
hl("Normal", { fg = c.tx, bg = "NONE" })
hl("NormalFloat", { bg = "NONE" })
hl("FloatBorder", { fg = c.ui3, bg = "NONE" })
hl("FloatTitle", { fg = c.cyan, bg = "NONE" })
hl("NormalNC", {})
hl("Pmenu", { fg = c.tx, bg = "NONE" })
hl("PmenuSel", { bg = c.bg2 })
hl("PmenuKind", { fg = c.tx2, bg = "NONE" })
hl("PmenuKindSel", { link = "PmenuSel" })
hl("PmenuExtra", { link = "Pmenu" })
hl("PmenuExtraSel", { link = "PmenuSel" })
hl("PmenuSbar", { link = "Pmenu" })
hl("PmenuThumb", { bg = c.tx3 })
hl("PmenuMatch", { fg = c.tx2, bold = true })
hl("PmenuMatchSelect", { link = "PmenuMatch" })
hl("ComplMatchIns", {})
hl("Question", { fg = c.blue })
hl("QuickFixLine", { fg = c.cyan })
hl("Search", { bg = c.ui2 })
hl("SnippetTabstop", { link = "Visual" })
hl("SpecialKey", { fg = c.tx3 })
hl("SpellBad", { sp = c.red, undercurl = true })
hl("SpellCap", { sp = c.yellow, undercurl = true })
hl("SpellLocal", { sp = c.cyan, undercurl = true })
hl("SpellRare", { sp = c.purple, undercurl = true })
hl("StatusLine", { bg = "NONE" })
hl("StatusLineNC", { fg = c.tx3, bg = c.bg2 })
hl("StatusLineTerm", { link = "StatusLine" })
hl("StatusLineTermNC", { link = "StatusLineNC" })
hl("TabLine", { link = "StatusLineNC" })
hl("TabLineFill", { link = "TabLine" })
hl("TabLineSel", { bold = true })
hl("Title", { bold = true })
hl("Visual", { bg = c.blue4 })
hl("VisualNOS", { link = "Visual" })
hl("WarningMsg", { fg = c.orange })
hl("Whitespace", { link = "NonText" })
hl("WildMenu", { link = "PmenuSel" })
hl("WinBar", { link = "StatusLine" })
hl("WinBarNC", { link = "StatusLineNC" })

-- Syntax highlights (:help group-name)
hl("Comment", { fg = c.tx3 })
hl("Constant", { fg = c.yellow })
hl("String", { fg = c.cyan })
hl("Character", { fg = c.orange })
hl("Number", { fg = c.purple })
hl("Boolean", { fg = c.orange })
hl("Float", { link = "Number" })

hl("Identifier", { fg = c.tx })
hl("Function", { fg = c.orange })

hl("Statement", { link = "Keyword" })
hl("Conditional", { link = "Keyword" })
hl("Repeat", { link = "Keyword" })
hl("Label", { link = "Keyword" })
hl("Operator", { fg = c.tx2 })
hl("Keyword", { fg = c.green })
hl("Exception", { link = "Keyword" })

hl("PreProc", { fg = c.orange })
hl("Include", { fg = c.cyan })
hl("Define", { link = "PreProc" })
hl("Macro", { fg = c.purple })
hl("PreCondit", { link = "PreProc" })

hl("Type", { fg = c.purple })
hl("StorageClass", { link = "Type" })
hl("Structure", { link = "Type" })
hl("Typedef", { link = "Type" })

hl("Special", { fg = c.orange })
hl("SpecialChar", { link = "Special" })
hl("Tag", { link = "Special" })
hl("Delimiter", { link = "Special" })
hl("SpecialComment", { link = "Special" })
hl("Debug", { link = "Special" })

hl("Underlined", { underline = true })
hl("Ignore", { fg = c.tx3 })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.cyan, bold = true })

hl("Added", { fg = c.green })
hl("Changed", { fg = c.yellow })
hl("Removed", { fg = c.red })

-- Diagnostic highlights (:help diagnostic-highlights)
hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.orange })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.tx2 })
hl("DiagnosticOk", { fg = c.green })

hl("DiagnosticVirtualTextError", { link = "DiagnosticError" })
hl("DiagnosticVirtualTextWarn", { link = "DiagnosticWarn" })
hl("DiagnosticVirtualTextInfo", { link = "DiagnosticInfo" })
hl("DiagnosticVirtualTextHint", { link = "DiagnosticHint" })
hl("DiagnosticVirtualTextOk", { link = "DiagnosticOk" })

hl("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.orange, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.blue, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.tx2, undercurl = true })
hl("DiagnosticUnderlineOk", { sp = c.green, undercurl = true })

hl("DiagnosticFloatingError", { link = "DiagnosticError" })
hl("DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
hl("DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
hl("DiagnosticFloatingHint", { link = "DiagnosticHint" })
hl("DiagnosticFloatingOk", { link = "DiagnosticOk" })

hl("DiagnosticSignError", { link = "DiagnosticError" })
hl("DiagnosticSignWarn", { link = "DiagnosticWarn" })
hl("DiagnosticSignInfo", { link = "DiagnosticInfo" })
hl("DiagnosticSignHint", { link = "DiagnosticHint" })
hl("DiagnosticSignOk", { link = "DiagnosticOk" })

hl("DiagnosticDeprecated", { sp = c.red, strikethrough = true })
hl("DiagnosticUnnecessary", { link = "Comment" })

-- Treesitter highlights (:help treesitter-highlight-groups)
hl("@variable", { fg = c.blue })
hl("@variable.builtin", { fg = c.magenta })
hl("@variable.parameter", { fg = c.tx })
hl("@variable.parameter.builtin", { fg = c.magenta })
hl("@variable.member", { fg = c.tx })

hl("@constant", { link = "Constant" })
hl("@constant.builtin", { fg = c.orange })
hl("@constant.macro", { link = "PreProc" })

hl("@module", { link = "Structure" })
hl("@module.builtin", { link = "Special" })
hl("@label", { link = "Label" })

hl("@string", { link = "String" })
hl("@string.documentation", { link = "String" })
hl("@string.regexp", { link = "Special" })
hl("@string.escape", { fg = c.purple })
hl("@string.special", { link = "SpecialChar" })
hl("@string.special.symbol", { link = "Special" })
hl("@string.special.path", { link = "Special" })
hl("@string.special.url", { link = "Underlined" })

hl("@character", { link = "Character" })
hl("@character.special", { link = "Special" })

hl("@boolean", { link = "Boolean" })
hl("@number", { link = "Number" })
hl("@float", { link = "Float" })

hl("@type", { link = "Type" })
hl("@type.builtin", { link = "Special" })
hl("@type.definition", { link = "Type" })

hl("@attribute", { fg = c.tx2 })
hl("@attribute.builtin", { link = "Special" })
hl("@property", { fg = c.tx })

hl("@function", { link = "Function" })
hl("@function.builtin", { fg = c.purple })
hl("@function.call", { link = "Function" })
hl("@function.macro", { fg = c.purple })

hl("@function.method", { link = "Function" })
hl("@function.method.call", { link = "Function" })

hl("@constructor", { link = "Special" })
hl("@operator", { link = "Operator" })

hl("@keyword", { link = "Keyword" })
hl("@keyword.coroutine", { link = "Keyword" })
hl("@keyword.function", { link = "Keyword" })
hl("@keyword.operator", { link = "Keyword" })
hl("@keyword.import", { fg = c.red })
hl("@keyword.type", { link = "Type" })
hl("@keyword.modifier", { link = "Keyword" })
hl("@keyword.repeat", { link = "Repeat" })
hl("@keyword.return", { link = "Keyword" })
hl("@keyword.debug", { link = "Debug" })
hl("@keyword.exception", { link = "Exception" })

hl("@keyword.conditional", { link = "Conditional" })
hl("@keyword.conditional.ternary", { link = "Conditional" })

hl("@keyword.directive", { link = "PreProc" })
hl("@keyword.directive.define", { link = "PreProc" })

hl("@punctuation.delimiter", { fg = c.tx2 })
hl("@punctuation.bracket", { fg = c.tx2 })
hl("@punctuation.special", { link = "Special" })

hl("@comment", { link = "Comment" })
hl("@comment.documentation", { link = "Comment" })

hl("@comment.error", { link = "DiagnosticError" })
hl("@comment.warning", { link = "DiagnosticWarn" })
hl("@comment.todo", { link = "Todo" })
hl("@comment.note", { link = "DiagnosticInfo" })

hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })

hl("@markup.heading", { link = "Title" })
hl("@markup.heading.1", { link = "Title" })
hl("@markup.heading.2", { link = "Title" })
hl("@markup.heading.3", { link = "Title" })
hl("@markup.heading.4", { link = "Title" })
hl("@markup.heading.5", { link = "Title" })
hl("@markup.heading.6", { link = "Title" })

hl("@markup.quote", { italic = true })
hl("@markup.math", { link = "Special" })

hl("@markup.link", { fg = c.cyan, underline = true })
hl("@markup.link.label", { link = "@markup.link" })
hl("@markup.link.url", { link = "@markup.link" })

hl("@markup.raw", { bg = c.bg2 })
hl("@markup.raw.block", { link = "@markup.raw" })

hl("@markup.list", { fg = c.tx2 })
hl("@markup.list.checked", { fg = c.green, bg = c.green4 })
hl("@markup.list.unchecked", { fg = c.tx2, bg = c.bg2 })

hl("@diff.plus", { link = "Added" })
hl("@diff.minus", { link = "Removed" })
hl("@diff.delta", { link = "Changed" })

hl("@tag", { fg = c.blue })
hl("@tag.builtin", { fg = c.magenta })
hl("@tag.tsx", { link = "@function" })
hl("@tag.attribute", { fg = c.blue })
hl("@tag.delimiter", { fg = c.tx2 })

-- LSP semantic token highlights
hl("@lsp.type.comment", { link = "@comment" })
hl("@lsp.type.enum", { link = "@type" })
hl("@lsp.type.enumMember", { link = "@constant" })
hl("@lsp.type.interface", { fg = c.cyan })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.namespace", { link = "@module" })
hl("@lsp.type.parameter", { link = "@variable.parameter" })
hl("@lsp.type.property", { link = "@property" })
hl("@lsp.type.variable", { link = "@variable" })
hl("@lsp.type.macro", { fg = c.purple })
hl("@lsp.type.method", { link = "@function.method" })
hl("@lsp.type.number", { link = "@number" })
hl("@lsp.type.operator", { link = "@operator" })
hl("@lsp.type.string", { link = "@string" })
hl("@lsp.type.struct", { link = "@type" })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { link = "@type.definition" })
hl("@lsp.type.decorator", { link = "@attribute" })
hl("@lsp.type.builtinType", { link = "@type.builtin" })
hl("@lsp.type.function", { link = "@function" })
hl("@lsp.type.class", { link = "@type" })

-- Custom statusline highlights
hl("StatusLineModeN", { fg = c.blue })
hl("StatusLineModeI", { fg = c.green })
hl("StatusLineModeV", { fg = c.magenta })
hl("StatusLineModeR", { fg = c.red })
hl("StatusLineModeC", { fg = c.orange })
hl("StatusLineModeT", { fg = c.green })

-- gitsigns.nvim highlights (:help gitsigns-highlight-groups)
hl("GitSignsDeleteLn", { link = "DiffDelete" })
hl("GitSignsStagedAdd", { fg = c.green3 })
hl("GitSignsStagedChange", { fg = c.yellow3 })
hl("GitSignsStagedDelete", { fg = c.red3 })
hl("GitSignsStagedChangedelete", { link = "GitSignsStagedChange" })
hl("GitSignsStagedTopdelete", { link = "GitSignsStagedDelete" })
hl("GitSignsStagedUntracked", { link = "GitSignsStagedAdd" })
hl("GitSignsStagedAddNr", { link = "GitSignsStagedAdd" })
hl("GitSignsStagedChangeNr", { link = "GitSignsStagedChange" })
hl("GitSignsStagedDeleteNr", { link = "GitSignsStagedDelete" })
hl("GitSignsStagedChangedeleteNr", { link = "GitSignsStagedChange" })
hl("GitSignsStagedTopdeleteNr", { link = "GitSignsStagedDelete" })
hl("GitSignsStagedUntrackedNr", { link = "GitSignsStagedAdd" })
hl("GitSignsStagedAddLn", { fg = c.green3, bg = c.green4 })
hl("GitSignsStagedChangeLn", { fg = c.yellow3, bg = c.yellow4 })
hl("GitSignsStagedDeleteLn", { fg = c.red3, bg = c.red4 })
hl("GitSignsStagedChangedeleteLn", { link = "GitSignsStagedChangeLn" })
hl("GitSignsStagedTopdeleteLn", { link = "GitSignsStagedDeleteLn" })
hl("GitSignsStagedUntrackedLn", { link = "GitSignsStagedAddLn" })
hl("GitSignsStagedAddCul", { link = "GitSignsStagedAdd" })
hl("GitSignsStagedChangeCul", { link = "GitSignsStagedChange" })
hl("GitSignsStagedDeleteCul", { link = "GitSignsStagedDelete" })
hl("GitSignsStagedChangedeleteCul", { link = "GitSignsStagedChange" })
hl("GitSignsStagedTopdeleteCul", { link = "GitSignsStagedDelete" })
hl("GitSignsStagedUntrackedCul", { link = "GitSignsStagedAdd" })

-- Flash
hl("FlashLabel", { fg = c.bg2, bg = c.red })

-- Snacks dashboard
hl("SnacksDashboardHeader", { fg = c.blue })
hl("SnacksDashboardIcon", { fg = c.cyan })
hl("SnacksDashboardDesc", { fg = c.cyan })
hl("SnacksDashboardKey", { fg = c.orange })

-- Treesitter Context
hl("TreesitterContextBottom", { underline = true, sp = c.ui })
hl("TreesitterContextLineNumberBottom", { underline = true, sp = c.ui })

-- Whichkey
hl("WhichKey", { fg = c.blue })
hl("WhichKeyDesc", { fg = c.cyan })
hl("WhichKeyGroup", { fg = c.orange })
