return {
	{ "vim-sleuth" },
	require("config.plugins.lazydev"),
	require("config.plugins.colorscheme"),
	require("config.plugins.snacks"),
	require("config.plugins.treesitter"),
	require("config.plugins.which-key"),
	require("config.plugins.lsp"),
	require("config.plugins.formatting"),
	require("config.plugins.git"),
	require("config.plugins.completion"),
	require("config.plugins.statusline"),
	require("config.plugins.autopairs"),
	require("config.plugins.comments"),
	require("config.plugins.surround"),
}
